'use client';

import Image from 'next/image';
import { useEffect, useMemo, useState } from 'react';
import {
  ArrowRight, BookOpen, Box, Braces, Check, ChevronRight, CircleHelp,
  Code2, Database, Gauge, Layers3, Lightbulb, Menu, Network, PlayCircle,
  RotateCw, Search, Sparkles, Wrench, X, Zap,
} from 'lucide-react';
import { Button } from '@/components/ui/button';

const chapters = [
  { id:'big-picture', n:'01', title:'The big picture', desc:'How Omniverse, USD, Kit, the Data Table and MCP connect', icon:Network },
  { id:'usd-language', n:'02', title:'The language of USD', desc:'Stage, prim, property, attribute, relationship and path', icon:Box },
  { id:'hierarchy', n:'03', title:'Hierarchy & transforms', desc:'Parents, children, axes, pivots and local versus world space', icon:Braces },
  { id:'composition', n:'04', title:'Layers & composition', desc:'How small files combine into one final scene', icon:Layers3 },
  { id:'references', n:'05', title:'References & variants', desc:'Reuse assets and switch configurations without duplication', icon:Database },
  { id:'materials', n:'06', title:'Materials & environments', desc:'Bindings, textures, lights, visibility and original appearance', icon:Sparkles },
  { id:'animation', n:'07', title:'Animation', desc:'Time codes, keyframes, interpolation, joints and wheel rotation', icon:PlayCircle },
  { id:'datatable', n:'08', title:'Data Table & UI', desc:'How editable JSON generates a reusable configurator', icon:Code2 },
  { id:'mcp', n:'09', title:'MCP & the router', desc:'How Codex safely talks to a running Composer scene', icon:Network },
  { id:'debugging', n:'10', title:'Debugging lessons', desc:'What the missing texture, snapping panel and wobbling wheels taught us', icon:Wrench },
  { id:'files', n:'11', title:'Your project map', desc:'What each important file owns and when to edit it', icon:Gauge },
  { id:'atlas', n:'12', title:'Visual project atlas', desc:'Explore the real Stage, layers, materials, Data Table and runtime', icon:Layers3 },
  { id:'concept-library', n:'13', title:'Complete concept library', desc:'Every concept learned in this project, collected and connected', icon:BookOpen },
  { id:'practice', n:'14', title:'Practice & quiz', desc:'Exercises and a knowledge check to make it stick', icon:CircleHelp },
];

const glossary = [
  ['Stage','The complete scene you see after USD combines all contributing layers.'],
  ['Prim','One named scene object or container, such as /World/Car or a wheel mesh.'],
  ['Property','A piece of information on a prim. Attributes and relationships are both properties.'],
  ['Attribute','A value such as visibility, color, translation or rotation. It may change over time.'],
  ['Relationship','A connection from one prim to another, such as a mesh binding to a material.'],
  ['Layer','A USD file containing opinions. Layers combine instead of forcing everything into one file.'],
  ['Opinion','A value authored by a layer: “this color is red” or “this prim is hidden.”'],
  ['Composition','The rule-driven process that combines layers, references and variants into the stage.'],
  ['Reference','A reusable link that brings another USD asset into a prim.'],
  ['Variant set','A named group of alternatives such as color = original/red/blue.'],
  ['Xform','A transformable prim used to position, rotate or scale itself and its descendants.'],
  ['Time sample','An attribute value stored at a particular frame/time code.'],
  ['Material binding','A relationship telling geometry which material should shade it.'],
  ['Schema','A recognized type and behavior contract, such as Mesh, Xform or DistantLight.'],
  ['MCP','A tool protocol that lets an assistant use clearly defined operations exposed by a server.'],
];

type ProjectConcept = { name:string; simple:string; project:string; remember:string };
type ConceptGroup = { title:string; subtitle:string; concepts:ProjectConcept[] };

const conceptGroups:ConceptGroup[] = [
  {title:'The complete system',subtitle:'The responsibilities that turn project data into visible pixels.',concepts:[
    {name:'OpenUSD',simple:'The scene-description system: a common language for objects, hierarchy, materials, composition and time.',project:'It stores and composes the ZAZ asset, its looks, variants and animation.',remember:'USD is the scene data—not the application window.'},
    {name:'Omniverse Composer',simple:'The Kit application used to open, inspect, edit and render a USD Stage.',project:'It gives us the viewport, Stage tree, Layer panel, Property panel and timeline.',remember:'Composer is the workshop; USD is what the workshop reads and writes.'},
    {name:'Kit',simple:'NVIDIA’s application framework for building Composer and custom tools.',project:'Our Mini DataTable Explorer is a Python Kit extension docked inside Composer.',remember:'Kit provides the application framework and extension lifecycle.'},
    {name:'OmniUI',simple:'Kit’s UI toolkit for windows, buttons, labels, scroll areas and layouts.',project:'It draws the configurator controls generated from datatable.json.',remember:'UI widgets display and collect choices; they do not contain the car capability.'},
    {name:'Viewport and RTX renderer',simple:'The viewport shows the Stage at the current time; the renderer converts geometry, materials and lights into pixels.',project:'The Desert Road, paint reflections and moving car are the composed result being rendered.',remember:'A changed pixel may come from geometry, a material, lighting, environment or time.'},
    {name:'Data Table',simple:'Project-specific JSON that describes what choices and actions should be exposed.',project:'It contains defaults, material maps, environment options and animation actions.',remember:'The table describes capabilities; it cannot create missing USD content by itself.'},
    {name:'MCP, router and bridge',simple:'MCP exposes tools; the router selects the correct backend; the live bridge touches the running Stage.',project:'Codex can inspect prims or trigger known actions through ports 9905 and 9910.',remember:'MCP is a controlled doorway beside the panel, not a replacement for USD or the Data Table.'},
  ]},
  {title:'USD scene language',subtitle:'The nouns used to identify and describe everything in the Stage.',concepts:[
    {name:'Stage',simple:'The final scene after USD composes every contributing file and opinion.',project:'working_scene.usda opens as one Stage even though many sublayers and a referenced car contribute.',remember:'A Stage is the composed result, not necessarily one file.'},
    {name:'Prim',simple:'One named, addressable scene object or container.',project:'/World/Car, a wheel Mesh and /World/Looks/RedPaint are all prims.',remember:'Prim means the thing; path means its address.'},
    {name:'Prim path',simple:'A case-sensitive address that locates a prim in the hierarchy.',project:'The panel targets paths such as /World/Car and /World/Looks/RedPaint.',remember:'Rename or reparent a prim and its path changes.'},
    {name:'Hierarchy',simple:'The parent-child tree of prims.',project:'Moving the parent /World/Car moves its doors, wheels, rig and body together.',remember:'Children inherit the transforms of their ancestors.'},
    {name:'Schema and prim type',simple:'A schema is a behavior/data contract; the type tells applications which schema a prim uses.',project:'The Stage tree shows Xform, Scope, SkelRoot, Mesh and Material types.',remember:'Type says what a prim is allowed to mean.'},
    {name:'Xform',simple:'A transformable prim that can position, rotate or scale an entire branch.',project:'/World/Car is the safe parent for whole-car driving motion.',remember:'Use a parent Xform when a complete assembly must move together.'},
    {name:'Mesh',simple:'A geometry prim containing polygon data such as points, faces and normals.',project:'The converted FBX retained separate body, door, hood, window and wheel meshes.',remember:'A Mesh is shape; its Material binding supplies appearance.'},
    {name:'Scope and Looks',simple:'A Scope is a folder-like organizational prim; Looks is the common scope for materials.',project:'/World/Looks contains RedPaint, BluePaint, wheel finishes and glass materials.',remember:'Organization prims do not need to draw geometry.'},
    {name:'Property',simple:'Any piece of authored data on a prim.',project:'Transforms, visibility and material connections appear as properties in Composer.',remember:'Attributes and relationships are the two important property families.'},
    {name:'Attribute',simple:'A property that stores a value, either once or at multiple times.',project:'Translation, joint rotation, visibility and shader roughness are attributes.',remember:'An attribute answers “what value?”'},
    {name:'Relationship',simple:'A property that points to another prim or object.',project:'material:binding connects a car mesh to a material prim.',remember:'A relationship answers “connected to what?”'},
    {name:'SkelRoot, skeleton and joints',simple:'Schemas that organize a rig and the transforms used to deform or articulate an asset.',project:'The original ZAZ rig supplies steering, door, front-trunk and rear-hood motion.',remember:'The mesh is visible shape; joints provide structured motion.'},
  ]},
  {title:'Layers and composition',subtitle:'How focused files cooperate without destroying source work.',concepts:[
    {name:'Layer',simple:'A USD file containing authored scene descriptions and opinions.',project:'Materials, assembly, variants, lights, environments and wheel animation live in focused layers.',remember:'A layer is an editable contribution, not a separate final scene.'},
    {name:'Root and authoring layer',simple:'The root anchors the Stage; the authoring target is where new edits are written.',project:'The Layer panel labels the open root as the authoring layer and lists its sublayers.',remember:'Always know which layer will receive your edit.'},
    {name:'Sublayer',simple:'A layer included by another layer so their contents compose together.',project:'working_scene.usda sublayers the ZAZ animation, variant, binding, material and environment files.',remember:'Sublayers stack opinions into one Stage.'},
    {name:'Opinion',simple:'A value or scene description authored by one layer.',project:'One layer can say color=red while a weaker source layer still contains the original binding.',remember:'USD composes opinions; it does not flatten every edit into the source.'},
    {name:'Strength and override',simple:'When opinions conflict, composition chooses the stronger one.',project:'A selected paint variant can override the imported material while preserving the source below.',remember:'Stronger means wins the conflict—not more important or larger.'},
    {name:'Reference',simple:'A composition arc that reuses content from another USD asset.',project:'/World/Car references zaz965_converted.usd instead of copying its 38 meshes.',remember:'A reference answers “which asset should appear here?”'},
    {name:'Variant set and selection',simple:'A named collection of alternatives with one active selection.',project:'color and wheel_finish expose original, painted or recreated finish choices.',remember:'A variant answers “which alternative of this asset?”'},
    {name:'Original variant',simple:'A pass-through alternative that avoids authoring a replacement opinion.',project:'Selecting original reveals the downloaded ZAZ material bindings again.',remember:'Restoration is a real product requirement, not an optional extra.'},
    {name:'USDA, USDC and USD',simple:'USDA is readable text; USDC is compact binary crate data; USD is the general ecosystem/extension.',project:'Small teaching layers use .usda while dense wheel samples use .usdc.',remember:'Choose representation based on readability, density and performance.'},
    {name:'Layer mute and lock',simple:'Mute temporarily removes a layer’s contribution; lock prevents edits.',project:'The eye and lock icons help isolate what each ZAZ layer contributes.',remember:'Muting is a diagnostic question: “What disappears without this layer?”'},
  ]},
  {title:'Transforms and spatial reasoning',subtitle:'Why an object can move correctly in math but wrongly on screen.',concepts:[
    {name:'Translation, rotation and scale',simple:'The basic operations that place, orient and size a prim.',project:'Driving translates /World/Car; doors and wheels use rotation.',remember:'A transform changes placement; it does not replace geometry.'},
    {name:'xformOp and operation order',simple:'USD stores transform operations in an ordered stack.',project:'Steering, axle pivot compensation and wheel spin must compose in the correct order.',remember:'The same operations in a different order can produce a different result.'},
    {name:'Local and world space',simple:'Local values are relative to a parent; world values include the full ancestor chain.',project:'The imported car’s forward direction is Z even though a programmer first assumed X.',remember:'Never guess an imported asset’s forward axis.'},
    {name:'Axis and gizmo',simple:'Axes define coordinate directions; the viewport gizmo exposes the selected prim’s orientation.',project:'Comparing the gizmo with the road revealed that driving should use axis="z".',remember:'An arrow is an axis, not automatically “forward.”'},
    {name:'Pivot and transform origin',simple:'The point around which rotation happens.',project:'A front wheel orbited above the door when rotation used a distant origin instead of the axle.',remember:'Correct rotation plus wrong pivot still looks wrong.'},
    {name:'Transform inheritance',simple:'A child receives its parent’s transform before applying its own.',project:'Front wheels combine car motion, steering-parent rotation, axle pivot and spin.',remember:'Debug the full transform chain, not only the final mesh.'},
    {name:'Reparenting',simple:'Moving a prim under a different parent changes its path and inherited transform context.',project:'Axle-centered spin children were placed beneath steering parents so both motions could coexist.',remember:'Reparenting changes both organization and mathematics.'},
    {name:'Units and distance',simple:'Scene units give numeric transforms a physical interpretation.',project:'Drive actions use distance ±350 in the Stage’s established unit scale.',remember:'A number is not a useful distance until you know the scene units.'},
  ]},
  {title:'Materials, textures and environments',subtitle:'How geometry acquires appearance and how the world changes that appearance.',concepts:[
    {name:'Material prim',simple:'A scene object holding or connecting a shading network.',project:'Paint, wheel, glass and original source materials live under Looks scopes.',remember:'A library preset becomes project content only when it exists in the Stage.'},
    {name:'Shader inputs',simple:'Parameters that control how a material reacts to light.',project:'BluePaint and ZAZWheelCream expose diffuse color, metallic, roughness and clearcoat values.',remember:'Materials are recipes made from several interacting inputs.'},
    {name:'Diffuse/base color',simple:'The primary surface color before lighting and reflections modify its appearance.',project:'The paint variants use different RGB values for silver, red, blue and white.',remember:'Screen color is not base color alone.'},
    {name:'Metallic, roughness and clearcoat',simple:'Metallic changes conductor behavior; roughness spreads reflections; clearcoat adds a top reflective layer.',project:'Wheel cream at metallic .35 and roughness .35 reflects differently from BluePaint at metallic 0 and roughness .5.',remember:'Two similar colors can look different because surface response differs.'},
    {name:'Opacity and IOR',simple:'Opacity controls transparency; index of refraction controls how light bends through transparent material.',project:'The main and door windows use a transparent glass material rather than body paint.',remember:'Do not recolor glass when the request is only body paint.'},
    {name:'Material binding',simple:'A relationship from geometry to the material that shades it.',project:'Color choices map friendly names to material paths and bind only the intended body meshes.',remember:'A material affects nothing until geometry is bound to it.'},
    {name:'Binding strength',simple:'Metadata that helps decide whether a broad or more specific descendant binding wins.',project:'Composer showed “Weaker than Descendants” on the selected door material binding.',remember:'Binding resolution follows composition rules too.'},
    {name:'Texture dependency and asset path',simple:'An image used by a shader must remain reachable through a valid path.',project:'A missing grid texture warning pointed to an obsolete local Kit cache path.',remember:'A valid-looking USD file can still have broken external dependencies.'},
    {name:'Source material vs project override',simple:'Imported bindings preserve authored detail; project materials selectively override intended surfaces.',project:'The original option keeps dirt and source texture detail while paint choices replace body appearance.',remember:'Override narrowly—body is not glass, rubber, chrome or interior.'},
    {name:'Environment, lighting and ground',simple:'Backdrop appearance, illumination, physical ground/contact and object visibility are separate concerns.',project:'Desert Road and Studio switching changes the environment safely without replacing the car Stage.',remember:'An environment image is not automatically a ground plane or light rig.'},
  ]},
  {title:'Animation and time',subtitle:'How poses become visible motion and why frame numbers need context.',concepts:[
    {name:'Time code and frame',simple:'A numbered address at which USD evaluates time-varying values.',project:'Open Doors occupies frames 1560–1848 on the master timeline.',remember:'Frame 1560 is an address, not a duration.'},
    {name:'Frames per second',simple:'The rate used to convert frame differences into elapsed seconds.',project:'At 24 fps, (1632−1560)/24 = 3 seconds after the Open Doors clip begins.',remember:'Elapsed time comes from the difference between frames.'},
    {name:'Global frame and local clip time',simple:'A clip can start far along the master timeline while its own local time starts at zero.',project:'Global frame 1560 equals local time 0 for Open Doors.',remember:'Subtract the clip start before dividing by fps.'},
    {name:'Time sample and keyframe',simple:'An authored attribute value at a particular time; keyframes mark meaningful states.',project:'Door-joint rotations are sampled at closed, open, held and closed moments.',remember:'USD evaluates values between authored samples.'},
    {name:'Interpolation',simple:'The method used to calculate values between time samples.',project:'Door motion blends between closed and open; bad quaternion interpolation caused front-wheel wobble.',remember:'The values and the path between them both matter.'},
    {name:'Pose',simple:'One exact evaluated time held without playback.',project:'hold_doors stops at frame 1728 so both doors remain open.',remember:'A pose selects a moment; it does not show travel through time.'},
    {name:'Clip',simple:'A start/end time range that is played through.',project:'open_doors plays frames 1560–1848 so opening, holding and closing are visible.',remember:'Visible motion needs a changing timeline.'},
    {name:'Loop',simple:'Playback returns to the clip start after reaching its end.',project:'Open All, Doors and Hoods repeat a 12-second cycle.',remember:'Loop re-evaluates the same authored samples; it does not record again.'},
    {name:'Hold using repeated values',simple:'Keeping the same value at two separated times creates a period with no visual change.',project:'Doors stay open for 4 seconds and closed for 2 seconds inside the loop.',remember:'A hold still occupies time even though the value is unchanged.'},
    {name:'Skeleton and joint animation',simple:'Time-varying joint transforms articulate parts linked to a rig.',project:'The original FBX rig controls steering, doors, front trunk and rear hood.',remember:'Reuse a valid source rig when it already owns the correct pivots.'},
    {name:'Wheel spin and steering composition',simple:'Axle spin and steering are independent rotations that must live in a compatible hierarchy.',project:'Rear wheels only spin; front wheels combine steering parents with axle-centered spin children.',remember:'Separate responsibilities into transforms that compose cleanly.'},
    {name:'Quaternion continuity and dense sampling',simple:'Equivalent quaternion signs can interpolate along different paths; continuity and closer samples stabilize motion.',project:'The regenerated wheel layer removed front-tire jitter while preserving steering.',remember:'Stable endpoints do not guarantee stable interpolation.'},
    {name:'Driving plus wheel rotation',simple:'Believable driving combines parent translation with correctly directed wheel spin.',project:'drive_forward and drive_backward translate on Z for four seconds while reversing spin direction appropriately.',remember:'Vehicle movement and wheel animation are coordinated but separate properties.'},
  ]},
  {title:'Data-driven configuration and UI',subtitle:'How reusable interface code learns what this particular car supports.',concepts:[
    {name:'JSON configuration',simple:'Structured text that stores project choices independently of panel code.',project:'datatable.json is readable, editable and reloadable without rebuilding the extension.',remember:'Data is easier to change and audit when it is not hard-coded into widgets.'},
    {name:'Defaults',simple:'The selections used when the project or panel first loads.',project:'Original paint, original wheel finish and Desert Road establish the initial state.',remember:'A default should correspond to a real valid scene state.'},
    {name:'Control options',simple:'Lists describing which UI choices should be created.',project:'Environment options generate Desert Road and Studio controls.',remember:'Listing an option does not author the geometry or material behind it.'},
    {name:'Parts and layer roles',simple:'Part records identify scene targets; layer roles describe which concern owns each contribution.',project:'Body, wheels and movable panels map to real prim paths and focused USD layers.',remember:'The table-to-scene contract depends on accurate paths and ownership.'},
    {name:'Material lookup map',simple:'A dictionary that converts a friendly option name into an exact material prim path.',project:'red resolves to /World/Looks/RedPaint.',remember:'Human labels and machine addresses should be separated.'},
    {name:'Animation action record',simple:'Data describing an action id, label, mode and its pose or clip parameters.',project:'open_doors is a looping clip; hold_doors is a pose; drive_forward adds axis and distance.',remember:'The same UI renderer can support new actions when the action schema is clear.'},
    {name:'Resolver/builder',simple:'Logic that interprets table rows and produces a configuration or layer plan.',project:'mini_car_builder.py resolves selected trim, color, wheel finish and interior values.',remember:'The table stores facts; the resolver applies rules.'},
    {name:'Generated UI',simple:'The panel creates controls from data instead of manually coding every button.',project:'Changing labels or supported options can update the panel after Reload Table.',remember:'The UI reflects data; it is not the Data Table itself.'},
    {name:'Data-driven versus hard-coded controls',simple:'Both can work, but data-driven controls separate changing project facts from reusable interface behavior.',project:'We could code every ZAZ button directly, but the table lets another project reuse the same panel with different options.',remember:'The Data Table is not mandatory; it is valuable because it makes change cheaper and reuse safer.'},
    {name:'Docked and responsive panel layout',simple:'A tool panel must remain usable inside a narrow dock, not only as a wide floating window.',project:'Options were moved into grids and scrollable vertical sections so the viewport could keep its space.',remember:'Tool UX includes where the tool lives, not just whether its callbacks work.'},
    {name:'Safe UI rebuild lifecycle',simple:'Extension callbacks must avoid rebuilding widgets after their window is gone or during an invalid state.',project:'A guarded build wrapper catches panel construction errors and shows a useful message instead of destabilizing Composer.',remember:'UI lifecycle safety is part of application correctness.'},
    {name:'Relevant-control filtering',simple:'Controls should be hidden when they cannot produce a meaningful visible result.',project:'trim, interior and mirror controls are hidden because this FBX lacks replaceable corresponding assets.',remember:'A visible button is a promise; remove buttons that cannot keep it.'},
    {name:'Stable UI state',simple:'Updating content without rebuilding the whole panel preserves scroll, focus and user orientation.',project:'The snapping slider/panel bug was fixed by updating only changed labels and button states.',remember:'A correct result can still feel broken if the interface jumps after every click.'},
    {name:'Reload, watch and save',simple:'Reload rereads configuration, file watching detects changes, and Save persists the Stage.',project:'The panel can reload datatable.json and save working_scene.usda for the next session.',remember:'Live state and durable state are different.'},
  ]},
  {title:'Automation, safety and persistence',subtitle:'How external tools operate the scene without losing control of scope.',concepts:[
    {name:'Tool contract',simple:'An MCP tool has a defined name, inputs and result instead of free-form access.',project:'Scene summary, prim inspection, variant selection and animation playback are exposed as bounded operations.',remember:'A narrow tool is easier to validate and safer to automate.'},
    {name:'Router',simple:'A single endpoint that forwards requests to scene or knowledge backends.',project:'http://127.0.0.1:9905/mcp is the shared front door.',remember:'One front door does not mean every backend is the same responsibility.'},
    {name:'Live Composer bridge',simple:'A service inside/near Composer that applies requested operations to the active Stage.',project:'The router reaches the bridge at http://127.0.0.1:9910/rpc.',remember:'The router listening does not prove Composer is open.'},
    {name:'Inspection before mutation',simple:'Read the current Stage, target path and property before changing them.',project:'We inspected axes, pivots, materials and layers before fixing movement and appearance.',remember:'The cheapest safe fix begins with the smallest accurate diagnosis.'},
    {name:'Dry run',simple:'A preview of a broad or destructive action without committing the mutation.',project:'Router actions should use dry_run when the operation supports it.',remember:'Verify the target and intended effect before a risky change.'},
    {name:'Action discovery',simple:'Ask the scene which named actions it supports instead of guessing.',project:'scene_animation_actions lists the ZAZ actions before scene_animation_play runs one.',remember:'Capability discovery keeps clients reusable across projects.'},
    {name:'Knowledge routing',simple:'Technical questions can be sent to specialized USD, Kit, OmniUI, Isaac or Bowerbot knowledge sources.',project:'The shared router remains one entry point while preserving backend specialization.',remember:'Knowledge answers and live scene mutations are different tool categories.'},
    {name:'Persistence and restart',simple:'Saving captures Stage edits; launcher scripts restore services and reopen the project.',project:'working_scene.usda plus start-omniverse.ps1 -LaunchComposer lets the demo survive restarts.',remember:'If it only exists in memory, it is not yet a durable project result.'},
    {name:'Shared context versus project context',simple:'Reusable infrastructure and lessons belong in shared notes; scene paths and decisions belong to the individual project.',project:'OMNIVERSE_WORKSPACE_CONTEXT.md explains the common router and startup stack, while the ZAZ files describe this demo.',remember:'Reuse the foundation without accidentally continuing or modifying the wrong project.'},
  ]},
  {title:'Debugging and workflow lessons',subtitle:'The mistakes that turned into reusable engineering rules.',concepts:[
    {name:'Symptom-first diagnosis',simple:'Describe exactly what moved, disappeared, changed color or jumped before editing code.',project:'Sideways motion, orbiting wheels and front-only jitter each pointed to different causes.',remember:'Similar-looking bugs can live in space, time, paths, materials or composition.'},
    {name:'Missing texture warning',simple:'Trace the report from owning prim to shader input to unresolved asset path.',project:'An old Kit-cache path caused the missing grid texture.',remember:'Do not treat every material warning as a geometry problem.'},
    {name:'Wireframe versus grid',simple:'Mesh wireframe and the viewport ground/grid overlay are separate display controls.',project:'Shift+W toggled the accidental wireframe overlay; the eye-menu Grid checkbox did not.',remember:'Name the visual overlay before toggling random visibility controls.'},
    {name:'Sample scene versus reusable asset',simple:'Opening a complete sample can replace the workspace; importing a material or asset contributes only the needed content.',project:'Double-clicking a Configurator Sample changed the environment, so it was inspected separately.',remember:'Open samples as references; bring only required assets into the real Stage.'},
    {name:'Safe environment switching',simple:'Toggle known environment branches or selections instead of replacing the root Stage.',project:'Desert Road and Studio switch without removing the configured car.',remember:'An environment control should preserve the product assembly.'},
    {name:'Wrong movement axis',simple:'The command may be correct but aimed along the wrong coordinate direction.',project:'Forward used X first; inspecting the imported ZAZ showed forward is Z.',remember:'Test asset orientation, not naming assumptions.'},
    {name:'Wrong wheel pivot',simple:'A rotating mesh orbits when its transform origin is away from the axle.',project:'The displaced front tire proved the pivot chain was wrong.',remember:'Inspect the center of rotation before changing rotation values.'},
    {name:'Front-wheel jitter',simple:'Extra steering transforms make interpolation problems visible that rear wheels do not share.',project:'Quaternion continuity and dense samples stabilized the front tires.',remember:'Compare stable and unstable siblings to isolate the extra transform responsibility.'},
    {name:'Validation',simple:'Automated checks confirm required prims, layers, variants, bindings and time samples.',project:'validate_usd_stack.py reports the composed ZAZ stack and expected capabilities.',remember:'A screenshot proves appearance once; validation protects the structure repeatedly.'},
    {name:'Change ownership',simple:'Edit the smallest file that owns the requested concern.',project:'Paint variants, generated animation, panel behavior and project options live in different files.',remember:'Do not fix a Data Table label inside a binary animation layer.'},
  ]},
  {title:'The ZAZ-965 project pipeline',subtitle:'The exact journey from downloaded asset to reusable learning application.',concepts:[
    {name:'Minimal practice prototype',simple:'A cube can teach Stage, prim, transform, material and binding concepts before a complex asset is introduced.',project:'The early demo used a cube and RedMaterial to prove the table-to-scene flow before the real ZAZ conversion.',remember:'Start with the smallest object that can prove the pipeline idea.'},
    {name:'FBX source and conversion',simple:'Source content is converted into native USD so Composer can compose and extend it.',project:'The ZAZ FBX became assets/zaz965/zaz965_converted.usd.',remember:'Record provenance and preserve the unmodified source asset.'},
    {name:'Separated source parts',simple:'Independent meshes make selective materials and motion possible.',project:'Conversion retained 38 meshes including doors, windows, both hoods, four road wheels and a spare.',remember:'Configuration quality depends on how the source asset is structured.'},
    {name:'Layered specialization',simple:'Each project layer adds one focused concern over the referenced source.',project:'Assembly, metadata, materials, fixed bindings, variants, environments, lights and wheel animation remain separable.',remember:'Generated or experimental work should not overwrite the source asset.'},
    {name:'Capability before control',simple:'Author and validate a real USD capability before adding its UI option.',project:'Paint materials, environment branches and animation ranges existed before the table exposed buttons.',remember:'Build the engine before adding the dashboard switch.'},
    {name:'Complete click-to-pixel flow',simple:'A user choice travels through data, UI callback, USD opinion, composition and rendering.',project:'Red button → table lookup → color variant → material binding → composed RedPaint → RTX pixels.',remember:'Trace every bug through the full responsibility chain.'},
    {name:'Complete asset-to-application flow',simple:'A production-like result is a chain of source, conversion, composition, control and presentation.',project:'FBX → converted USD → referenced Car → specialized layers → working Stage → DataTable panel/MCP → viewport.',remember:'The project is an application around scene data, not merely a car file.'},
  ]},
];

const quiz = [
  { q:'What is the Data Table in our demo?', options:['The 3D car mesh','A configuration blueprint read by the UI','The renderer'], answer:1, why:'It describes controls, defaults, paths and actions. The panel code reads it; the USD scene performs the real changes.' },
  { q:'Which USD idea lets “red” and “original” exist as selectable alternatives?', options:['Variant set','Camera','Payload cache'], answer:0, why:'The color variant set stores named alternatives, and selecting one changes the composed result.' },
  { q:'Why did a front wheel appear to orbit instead of spin?', options:['Its texture was too large','Rotation happened around the wrong pivot/transform space','The Data Table was missing'], answer:1, why:'Rotation is always around an origin. If the transform origin is not at the axle, the wheel travels around that origin.' },
  { q:'What does a stronger USD layer do?', options:['Uses more GPU memory','Wins when it authors a competing opinion','Deletes weaker layers'], answer:1, why:'Layers remain separate. Composition resolves conflicts by strength; weaker layers are not destroyed.' },
  { q:'Why keep the “original” appearance option?', options:['It preserves the imported source bindings','It improves physics','It restarts Composer'], answer:0, why:'An empty/pass-through original variant allows the downloaded model’s source material bindings to remain visible.' },
];

function Code({ children }: { children: React.ReactNode }) {
  return <pre className="code"><code>{children}</code></pre>;
}

function Callout({ title, children, kind='idea' }: { title:string; children:React.ReactNode; kind?:'idea'|'project'|'careful' }) {
  const Icon = kind==='careful' ? Wrench : kind==='project' ? Zap : Lightbulb;
  return <aside className={`callout ${kind}`}><Icon/><div><strong>{title}</strong><div>{children}</div></div></aside>;
}

function ScreenshotLesson({ src, alt, title, caption, points }: { src:string; alt:string; title:string; caption:string; points:{label:string; text:string}[] }) {
  return <figure className="screenshot-lesson"><div className="shot-image"><img src={src} alt={alt}/><span>Real project screenshot</span></div><figcaption><p className="shot-title">{title}</p><p>{caption}</p><div className="shot-points">{points.map((point,i)=><div key={point.label}><b>{i+1}</b><p><strong>{point.label}</strong>{point.text}</p></div>)}</div></figcaption></figure>;
}

const atlasViews = {
  stage:{title:'Stage hierarchy',blurb:'The Stage tree is the composed address book. Containers organize; child prims inherit transforms; paths let scripts and MCP target exact objects.',tree:['/World','├─ /World/Car  → referenced ZAZ asset','│  ├─ skeleton + joints','│  ├─ body, doors, hoods and windows','│  └─ steering parents + wheel spin children','├─ /World/Looks  → paint and wheel materials','└─ /Environment  → Desert Road or Studio']},
  layers:{title:'Layer stack',blurb:'The final Stage is assembled from focused files. Higher layers can override opinions below without destroying them.',tree:['STRONG  working_scene.usda  → assembly + selections','↑  zaz965_wheel_spin.usdc  → dense wheel samples','↑  mini_carpaint_variants.usda  → body choices','↑  mini_model_variants.usda  → wheel choices','BASE  zaz965_converted.usd  → source mesh, rig, textures']},
  flow:{title:'One click through the system',blurb:'Follow a Red button click from configuration to pixels. Each box owns one responsibility.',tree:['datatable.json says “red” is available','↓ panel creates a Red button','↓ button selects color = red','↓ USD variant authors a stronger material binding','↓ composition resolves /World/Looks/RedPaint','↓ RTX renderer draws the new result']}
};

function VisualAtlas(){const [view,setView]=useState<keyof typeof atlasViews>('stage');const item=atlasViews[view];return <div className="visual-atlas"><div className="atlas-tabs">{Object.entries(atlasViews).map(([key,value])=><button className={view===key?'active':''} onClick={()=>setView(key as keyof typeof atlasViews)} key={key}>{value.title}</button>)}</div><div className="atlas-board"><div><p className="eyebrow">Interactive diagram</p><h3>{item.title}</h3><p>{item.blurb}</p></div><pre>{item.tree.join('\n')}</pre></div></div>}

function ScreenCard({src,title,children}:{src:string;title:string;children:React.ReactNode}){const [zoomed,setZoomed]=useState(false);useEffect(()=>{if(!zoomed)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setZoomed(false)};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[zoomed]);return <><details className="screen-card"><summary><span className="screen-image-button" role="button" tabIndex={0} aria-label={`Open large image: ${title}`} onClick={event=>{event.preventDefault();event.stopPropagation();setZoomed(true)}} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();event.stopPropagation();setZoomed(true)}}}><img src={src} alt={title}/><i>Click image to enlarge</i></span><span className="screen-copy"><b>{title}</b><small>Click this text to understand the screen</small></span><ChevronRight/></summary><div>{children}</div></details>{zoomed&&<div className="image-lightbox" role="dialog" aria-modal="true" aria-label={title} onClick={()=>setZoomed(false)}><button onClick={()=>setZoomed(false)} aria-label="Close large image"><X/> Close</button><figure onClick={event=>event.stopPropagation()}><img src={src} alt={title}/><figcaption>{title}</figcaption></figure></div>}</>}

function ConceptLibrary(){
  const [conceptQuery,setConceptQuery]=useState('');
  const normalized=conceptQuery.trim().toLowerCase();
  const total=conceptGroups.reduce((sum,group)=>sum+group.concepts.length,0);
  const visible=conceptGroups.map(group=>({...group,concepts:group.concepts.filter(item=>!normalized||`${group.title} ${item.name} ${item.simple} ${item.project} ${item.remember}`.toLowerCase().includes(normalized))})).filter(group=>group.concepts.length);
  const shown=visible.reduce((sum,group)=>sum+group.concepts.length,0);
  const slug=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
  return <div className="concept-library">
    <div className="concept-dashboard"><div><p className="eyebrow">Knowledge coverage</p><b>{total}</b><span>project concepts explained</span></div><div className="coverage-route"><span>Source</span><ChevronRight/><span>USD</span><ChevronRight/><span>Controls</span><ChevronRight/><span>Pixels</span></div></div>
    <Callout kind="project" title="How to use this section"><p>Read a category from top to bottom when you want the full mental model. When you forget one word, use the search box. Every card gives you three levels: a plain meaning, the exact ZAZ example, and one sentence worth remembering.</p></Callout>
    <label className="search concept-search"><Search/><input value={conceptQuery} onChange={event=>setConceptQuery(event.target.value)} placeholder="Search all concepts: pivot, reference, clip, MCP…"/><span>{shown}/{total}</span></label>
    {!normalized&&<nav className="concept-jump" aria-label="Concept categories">{conceptGroups.map(group=><a key={group.title} href={`#concept-${slug(group.title)}`}>{group.title}<small>{group.concepts.length}</small></a>)}</nav>}
    {visible.length?visible.map((group,groupIndex)=><section className="concept-group" id={`concept-${slug(group.title)}`} key={group.title}><header><span>{String(groupIndex+1).padStart(2,'0')}</span><div><h3>{group.title}</h3><p>{group.subtitle}</p></div><b>{group.concepts.length} concepts</b></header><div className="concept-cards">{group.concepts.map((item,index)=><article className="concept-card" key={item.name}><div className="concept-card-title"><span>{String(index+1).padStart(2,'0')}</span><h4>{item.name}</h4></div><div><b>In simple words</b><p>{item.simple}</p></div><div><b>In our ZAZ project</b><p>{item.project}</p></div><blockquote>{item.remember}</blockquote></article>)}</div></section>):<div className="concept-empty"><CircleHelp/><b>No concept matched “{conceptQuery}”</b><p>Try a shorter word such as layer, wheel, material, UI or frame.</p></div>}
  </div>
}

function Lesson({ id, eyebrow, title, intro, children, done, onDone }: { id:string; eyebrow:string; title:string; intro:string; children:React.ReactNode; done:boolean; onDone:()=>void }) {
  return <section id={id} className="lesson scroll-mt-24"><div className="lesson-head"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p className="lead">{intro}</p></div><Button onClick={onDone} variant={done?'secondary':'outline'} className={done?'done-btn':''}>{done?<><Check/> Completed</>:<>Mark complete</>}</Button></div>{children}</section>;
}

export default function Home() {
  const [completed, setCompleted] = useState<string[]>([]);
  const [menuOpen, setMenuOpen] = useState(false);
  const [query, setQuery] = useState('');
  const [answers, setAnswers] = useState<Record<number,number>>({});
  useEffect(()=>{ try { setCompleted(JSON.parse(localStorage.getItem('openusd-progress')||'[]')); } catch {} },[]);
  useEffect(()=>{ localStorage.setItem('openusd-progress',JSON.stringify(completed)); },[completed]);
  const toggle=(id:string)=>setCompleted(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);
  const score=quiz.reduce((n,q,i)=>n+(answers[i]===q.answer?1:0),0);
  const filteredGlossary=useMemo(()=>glossary.filter(([a,b])=>(a+' '+b).toLowerCase().includes(query.toLowerCase())),[query]);
  const percent=Math.round(completed.length/chapters.length*100);

  return <main className="min-h-screen">
    <header className="site-header"><div className="header-inner"><a href="#top" className="brand"><span><Box size={19}/></span><div><b>OpenUSD Garage</b><small>ZAZ-965 learning lab</small></div></a><div className="header-progress"><span>{percent}% learned</span><div><i style={{width:`${percent}%`}}/></div></div><button className="menu-button" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle chapter menu">{menuOpen?<X/>:<Menu/>}</button></div></header>

    <section id="top" className="hero"><div><p className="hero-kicker"><BookOpen/> Learn by rebuilding what you made</p><h1>Understand your entire <em>Omniverse mini demo.</em></h1><p className="hero-copy">A friendly, detailed guide to OpenUSD, layers, variants, animation, materials, Kit UI, Data Tables, MCP—and the small decisions that made your ZAZ-965 configurator work.</p><div className="hero-actions"><a href="#big-picture" className="primary-link">Start learning <ArrowRight/></a><a href="#course-map" className="secondary-link"><PlayCircle/> View course map</a></div><div className="hero-stats"><div><b>14</b><span>chapters</span></div><div><b>100</b><span>concepts</span></div><div><b>Real</b><span>project examples</span></div></div></div><figure><Image src="/zaz-desert.png" alt="The ZAZ-965 demo car in the Desert Road environment" width={1650} height={755} priority/><figcaption><span>Your working example</span>One car. The whole OpenUSD workflow.</figcaption></figure></section>

    <section id="course-map" className="course-map"><div className="wide"><p className="eyebrow">Course map</p><h2>Start simple. Build the mental model layer by layer.</h2><div className="chapter-grid">{chapters.map(c=><a href={`#${c.id}`} key={c.id} className="chapter-card"><span>{c.n}</span><c.icon/><div><h3>{c.title}</h3><p>{c.desc}</p></div>{completed.includes(c.id)&&<Check className="complete-check"/>}</a>)}</div></div></section>

    <div className="course-shell">
      <aside className={`toc ${menuOpen?'open':''}`}><div className="toc-inner"><p>Chapters</p>{chapters.map(c=><a href={`#${c.id}`} onClick={()=>setMenuOpen(false)} key={c.id} className={completed.includes(c.id)?'is-done':''}><span>{completed.includes(c.id)?<Check/>:c.n}</span>{c.title}</a>)}</div></aside>
      <article className="course-content">
        <Lesson id="big-picture" eyebrow="Chapter 01 · Orientation" title="First, see the whole machine" intro="Before learning individual terms, understand what each major piece is responsible for. This prevents the most common beginner confusion: treating Omniverse, USD, the UI and MCP as if they are the same thing." done={completed.includes('big-picture')} onDone={()=>toggle('big-picture')}>
          <div className="flow"><div><Database/><b>Data Table</b><span>What choices exist?</span></div><ChevronRight/><div><Code2/><b>Kit panel</b><span>Show controls and react to clicks</span></div><ChevronRight/><div><Layers3/><b>USD stage</b><span>Compose and display the scene</span></div><ChevronRight/><div><Sparkles/><b>Renderer</b><span>Turn scene data into pixels</span></div></div>
          <h3>The five responsibilities</h3><div className="numbered"><div><span>1</span><p><b>OpenUSD is the scene language.</b> It describes objects, transforms, materials, variants, animation and how many files combine.</p></div><div><span>2</span><p><b>Omniverse Composer is the application.</b> It loads and edits the USD stage, provides a viewport, timeline and property panels, and renders the result.</p></div><div><span>3</span><p><b>Kit is the application framework.</b> Composer itself is built with Kit. Our Python extension adds the custom configurator panel.</p></div><div><span>4</span><p><b>The Data Table is project configuration.</b> It tells the reusable panel which choices and actions this particular car supports.</p></div><div><span>5</span><p><b>MCP is an automation doorway.</b> It exposes specific scene operations so Codex can inspect or change a running Composer scene.</p></div></div>
          <Callout title="The restaurant analogy"><p><b>USD is the kitchen and recipe system.</b> The Data Table is the menu. The Kit panel is the waiter taking your selection. Composer is the whole restaurant where the result is prepared and shown. MCP is a controlled service entrance used by an automation assistant.</p></Callout>
          <Callout kind="project" title="In our ZAZ project"><p>Clicking <b>Red</b> starts in the panel. The panel learned that “red” exists from <code>datatable.json</code>. It asks the stage to select the red color variant. USD composition resolves the result, the material binding changes, and the renderer displays red pixels.</p></Callout>
        </Lesson>

        <Lesson id="usd-language" eyebrow="Chapter 02 · Foundations" title="Learn the nouns of OpenUSD" intro="USD becomes much easier when you can name what you are looking at. These terms are small, but almost every advanced feature is built from them." done={completed.includes('usd-language')} onDone={()=>toggle('usd-language')}>
          <h3>Stage: the final composed scene</h3><p>A <b>stage</b> is the scene as an application understands it after composition. It may be assembled from many files, but Composer presents it as one hierarchy. Think of a finished web page assembled from HTML, CSS, images and scripts: the browser shows one page even though many resources contributed.</p>
          <h3>Prim: one addressable scene object</h3><p>A <b>prim</b> (short for primitive) is a named object or container. A prim can represent a car, mesh, camera, light, material or organizational group. Every prim has a unique path.</p>
          <Code>{`/World
/World/Car
/World/Car/ZAZ_965_fbx_skel
/World/Looks/RedPaint`}</Code>
          <p>The slash means hierarchy. <code>/World/Car</code> is a child of <code>/World</code>. A child inherits its parent’s transform, so moving <code>/World/Car</code> moves the entire car beneath it.</p>
          <div className="compare"><div><h4>Attribute</h4><p>A value owned by a prim: translation, visibility, color, intensity or a mesh’s points. Attributes can have one default value or time-sampled values.</p><code>visibility = "invisible"</code></div><div><h4>Relationship</h4><p>A connection to another prim. Material bindings are relationships: geometry points to the material that should shade it.</p><code>material:binding → /World/Looks/RedPaint</code></div></div>
          <h3>Prim types and schemas</h3><p>A prim’s type communicates intended behavior. An <b>Xform</b> can carry transforms. A <b>Mesh</b> carries polygons. A <b>DomeLight</b> emits environment light. USD schemas standardize these meanings so different applications agree.</p>
          <Callout kind="careful" title="Path accuracy matters"><p><code>/World/Car/Wheel</code> and <code>/World/car/Wheel</code> are different paths. A tool aimed at a wrong or renamed path cannot change the intended prim. That is why our Data Table stores exact USD paths for important parts.</p></Callout>
        </Lesson>

        <Lesson id="hierarchy" eyebrow="Chapter 03 · Space" title="Hierarchy, axes and pivots explain motion" intro="Most surprising movement bugs are not really animation bugs. They are misunderstandings about parent transforms, coordinate space or the point around which rotation occurs." done={completed.includes('hierarchy')} onDone={()=>toggle('hierarchy')}>
          <h3>Local space versus world space</h3><div className="compare"><div><h4>World space</h4><p>The global coordinate system of the whole stage. A world-space Z movement changes position along the stage’s Z axis.</p></div><div><h4>Local space</h4><p>The coordinate system inherited by an object from its parents. “Forward” for a rotated car may not match the world X axis.</p></div></div>
          <p>Our imported ZAZ faced along the <b>Z axis</b>. The first forward implementation used X, so the car moved sideways. The viewport gizmo revealed the correct orientation, and the Data Table action was changed to <code>axis: "z"</code>.</p>
          <ScreenshotLesson src="/car-axis-gizmo.png" alt="ZAZ-965 selected in Composer with its transform gizmo visible over the Desert Road" title="Read the gizmo before writing movement code" caption="This captured the sideways-motion investigation. The road gives us a visual definition of forward, while the colored gizmo tells us how the selected car prim is oriented in USD space." points={[{label:'The orange outline identifies the selected prim. ',text:'A transform applied at this parent moves the complete car hierarchy, not only one mesh.'},{label:'The colored arrows are axes, not driving directions. ',text:'We compare them with the road to discover which axis actually points forward.'},{label:'The fix belongs in project data. ',text:'Once Z was confirmed as forward, the drive action stored axis = z. The reusable movement code stayed generic.'}]}/>
          <h3>A pivot is the center of rotation</h3><p>Imagine pushing a door. It rotates around the hinge, not around its geometric center. Wheels rotate around their axles. If you rotate wheel geometry around a parent origin located elsewhere, the wheel <b>orbits</b> that origin like a moon instead of spinning in place.</p>
          <div className="formula"><span>Correct wheel motion</span><b>move to pivot → rotate → move back</b><small>or rotate an accurately positioned parent transform</small></div>
          <ScreenshotLesson src="/wheel-pivot-failure.png" alt="ZAZ-965 with its front wheel displaced above the door because it rotated around the wrong pivot" title="A perfect picture of the wrong pivot" caption="The tire did rotate—but around a point far from its axle. Rotation can therefore be mathematically valid and visually wrong at the same time." points={[{label:'The empty wheel well reveals the expected axle position. ',text:'That is the center around which the tire should spin.'},{label:'The tire above the door reveals the authored origin. ',text:'Its circular travel is evidence that a distant parent origin or uncompensated imported transform was used.'},{label:'Pivot compensation changes the transform chain. ',text:'Spin lives on an axle-centered child while the steering parent remains free to turn left and right.'}]}/>
          <h3>Transform inheritance</h3><p>If the steering joint rotates the front wheel left and right, and a child transform spins the wheel around its axle, the final motion is a composition of both transforms. The order matters. Our front wheels required pivot compensation beneath the steering parents so steering and axle spin could coexist.</p>
          <Code>{`worldTransform(wheelMesh) =
  worldTransform(car) × steeringTransform × axlePivot × spinRotation × localMeshTransform`}</Code>
          <p>Read this as a chain of coordinate systems. The car moves through the world; the steering parent aims the wheel; the axle pivot establishes the correct center; spin rotates around that center; and the imported mesh keeps its own local offset. Removing or reordering one transform changes the result.</p>
          <Callout kind="project" title="Why the rear wheels were easier"><p>The rear wheels did not have steering parents. They only needed axle rotation. The front wheels combined steering, imported joint transforms and added spin, so any axis or quaternion discontinuity became visible as wobble.</p></Callout>
        </Lesson>

        <Lesson id="composition" eyebrow="Chapter 04 · Core USD superpower" title="Layers combine without destroying each other" intro="Layering is the reason USD works well for teams and complex assets. Instead of repeatedly editing one giant scene, each concern can contribute its own opinions." done={completed.includes('composition')} onDone={()=>toggle('composition')}>
          <h3>What is an opinion?</h3><p>An <b>opinion</b> is a value authored in a layer. One layer might say the car is visible. Another might say its selected color variant is red. If multiple layers author the same property, USD’s composition rules determine which opinion wins.</p>
          <div className="layer-stack"><div><b>Strongest</b><span>working_scene.usda</span><small>Session choices and assembly</small></div><div><b>↑</b><span>zaz965_wheel_spin.usdc</span><small>Added animation samples</small></div><div><b>↑</b><span>mini_carpaint_variants.usda</span><small>Color choices</small></div><div><b>Weakest</b><span>Imported ZAZ asset</span><small>Source geometry, rig and materials</small></div></div>
          <p>“Strong” does not mean physically larger or more important. It means that when two opinions conflict, the stronger one is used in the composed result. The weaker opinion remains stored and can become visible again when the stronger one is removed.</p>
          <h3>Why our project uses separate layers</h3><ul><li>The downloaded car stays recoverable and recognizable.</li><li>Paint variants can change without touching animation.</li><li>Wheel spin can be regenerated without rebuilding materials.</li><li>Lights and environments can be edited independently.</li><li>A mistake can often be fixed by changing one small layer.</li></ul>
          <Callout title="Non-destructive editing"><p>Think of transparent sheets stacked on an overhead projector. Each sheet adds or replaces visible marks, but the sheets below remain intact. Removing the top sheet reveals what was underneath.</p></Callout>
          <h3>USDA versus USDC</h3><div className="compare"><div><h4>.usda</h4><p>Human-readable text. Excellent for learning, review and small authored layers.</p></div><div><h4>.usdc</h4><p>Binary “crate” format. Faster and more compact for heavier scene data and dense animation samples.</p></div></div>
        </Lesson>

        <Lesson id="references" eyebrow="Chapter 05 · Reuse & choices" title="References reuse; variants choose" intro="These two composition tools solve different problems. A reference brings an asset into a scene. A variant set keeps named alternatives on an asset." done={completed.includes('references')} onDone={()=>toggle('references')}>
          <h3>References</h3><p>A reference lets a prim reuse content defined elsewhere. Our <code>/World/Car</code> prim references the ZAZ asset instead of copying every mesh, material and animation into the assembly layer. If the source improves, scenes referencing it can receive that improvement.</p>
          <Code>{`def Xform "Car" (
    prepend references = @../assets/zaz965/zaz965.usd@
)
{
}`}</Code>
          <h3>Variant sets</h3><p>A variant set is like a named switchboard. The set <code>color</code> contains alternatives such as <code>original</code>, <code>red</code> and <code>blue</code>. Only the selected variant’s opinions participate.</p>
          <Code>{`variantSet "color" = {
  "original" { }          # source binding passes through
  "red"      { ... }      # bind RedPaint
  "blue"     { ... }      # bind BluePaint
}`}</Code>
          <p>The empty <code>original</code> variant is intentional. It does not mean “nothing exists.” It means this stronger layer adds no replacement binding, allowing the imported source material to remain visible.</p>
          <div className="compare"><div><h4>Reference asks</h4><p>“Which reusable asset should exist here?”</p><code>Bring in the ZAZ car</code></div><div><h4>Variant asks</h4><p>“Which authored alternative should this asset use?”</p><code>color = red</code></div></div>
          <Callout kind="careful" title="A button is not enough"><p>Adding <code>"green"</code> to the Data Table can create a Green button, but it cannot invent a green material or USD variant. The scene capability must exist, and then the Data Table exposes it to the UI.</p></Callout>
        </Lesson>

        <Lesson id="materials" eyebrow="Chapter 06 · Appearance" title="Materials shade geometry; environments shape the light" intro="A model’s appearance is a collaboration between geometry, material networks, texture files, lights, the environment and the renderer." done={completed.includes('materials')} onDone={()=>toggle('materials')}>
          <h3>Material binding</h3><p>A mesh does not usually contain “redness” itself. It is bound to a material prim. The material contains or connects to shader inputs such as base color, roughness, metallic response, normal detail and opacity.</p>
          <div className="flow compact"><div><Box/><b>Body mesh</b><span>Geometry</span></div><ChevronRight/><div><Network/><b>Binding</b><span>Relationship</span></div><ChevronRight/><div><Sparkles/><b>RedPaint</b><span>Shader network</span></div></div>
          <h3>Textures are external dependencies</h3><p>The missing grid-texture warning occurred because a material referenced an image using a path from an older Kit installation. USD successfully stored the path, but the file no longer existed at that location. This is similar to a web page whose image URL returns “not found.”</p>
          <ScreenshotLesson src="/missing-texture-warning.png" alt="Composer UsdToMdl warning showing a diffuse texture asset path that cannot be found" title="How to read the missing-texture warning" caption="The message contains a complete diagnosis: which system noticed the problem, which material prim owns it, which shader input is affected, and which path failed." points={[{label:'UsdToMdl is the reporting system. ',text:'It was translating USD shading data when the dependency could not be resolved.'},{label:'/Environment/Looks/Grid/Shader is the owner. ',text:'This proves the car is not the broken asset—the environment grid material is.'},{label:'diffuse_texture is the affected input. ',text:'Geometry can load while the shader loses the image supplying its surface color.'},{label:'The old Kit-cache path is the cause. ',text:'Moving installations made that fragile local dependency invalid.'}]}/>
          <Callout kind="careful" title="Portable asset rule"><p>Keep required textures inside a stable project asset folder and reference them with paths that remain valid when the project moves. A material can be perfectly authored and still render incorrectly if its image files are missing.</p></Callout>
          <h3>Environment switching</h3><p>The Desert Road and Studio options do not replace the whole stage. Our panel changes the <b>visibility</b> of environment prim groups. Desert Road shows <code>/Environment/hdr_projected_variants/desert_road_03</code> and hides studio ground/lights; Studio does the reverse.</p>
          <ScreenshotLesson src="/desert-road-scene.png" alt="Original beige ZAZ-965 on the Desert Road environment with its front and rear panels open" title="What an environment contributes" caption="The car geometry is unchanged. The improvement comes from projected scenery, sky illumination, a surface under the tires and reflections that match the surroundings." points={[{label:'Background and lighting agree. ',text:'The visible sky also influences illumination and reflections, helping the car feel placed rather than pasted.'},{label:'The road supplies scale and contact. ',text:'Lane markings, texture detail and tire shadows give strong depth and size cues.'},{label:'Light icons are scene helpers. ',text:'They represent authored light prims and are not physical objects in the final render.'},{label:'Animation remains independent. ',text:'Door and hood time samples keep working after the environment visibility choice changes.'}]}/>
          <h3>Lighting vocabulary</h3><ul><li><b>Dome or image-based light:</b> surrounds the scene with illumination sampled from an environment image.</li><li><b>Key light:</b> the main directional light defining form.</li><li><b>Fill light:</b> softens overly dark shadows.</li><li><b>Reflection:</b> bright surfaces seen by glossy materials; not the same thing as a side-mirror object.</li><li><b>Roughness:</b> controls whether highlights are sharp like polished metal or broad like worn paint.</li></ul>
          <Callout kind="project" title="Why we kept the aged beige original"><p>“Original” preserves the model’s imported material bindings, including its warm aged paint and cream/chrome wheels. Our red, blue and white options are deliberate overrides—not replacements for the source asset.</p></Callout>
          <ScreenshotLesson src="/original-zaz-material.png" alt="Close view of the ZAZ-965 original aged beige paint, dirty lower body and cream wheels" title="Original means source-authored—not plain beige" caption="This close view shows why a simple replacement color cannot recreate the downloaded model’s character. Several material channels and texture maps work together." points={[{label:'Base color carries variation. ',text:'The warm beige is not one perfectly flat RGB value.'},{label:'Roughness shapes highlights. ',text:'Broad reflections make the aged paint feel less polished than a new clearcoat.'},{label:'Dirt is spatial information. ',text:'Dark buildup near the lower body is mapped to exact regions through UVs.'},{label:'Different surfaces need different materials. ',text:'Body paint can change while glass, tires, chrome and source detail remain intact.'}]}/>
        </Lesson>

        <Lesson id="animation" eyebrow="Chapter 07 · Time" title="Animation is changing authored values over time" intro="USD animation is not a mysterious video clip. It is usually a collection of values stored at time codes, with interpolation filling the moments between them." done={completed.includes('animation')} onDone={()=>toggle('animation')}>
          <ScreenshotLesson src="/animation-controls.png" alt="Composer viewport and ZAZ animation panel with pose and sequence controls" title="The control panel is a remote control for stage time" caption="The buttons are not the animation itself. They choose a pose or configure timeline playback; the changing values already live on USD properties." points={[{label:'The viewport shows the evaluated result. ',text:'At the current frame Composer asks USD for every time-sampled value and redraws the car.'},{label:'The status line reports intention and time. ',text:'“Everything open (frame 480)” identifies one exact authored pose.'},{label:'Pose buttons jump; sequence buttons play. ',text:'A pose sets one frame. A sequence sets a range and starts the timeline so intermediate motion is visible.'},{label:'The scrollbar belongs to UI state. ',text:'Preserving widgets prevents controls such as Hold Open from snapping away after a click.'}]}/>
          <h3>Time codes and frames</h3><p>A stage defines a time range and a <b>timeCodesPerSecond</b> rate. At 24 time codes per second, 72 frames represent three seconds. A timeline moves the stage’s current time; USD evaluates time-sampled properties for that moment.</p>
          <div className="timeline"><div style={{left:'0%'}}><i/>0s<br/><b>closed</b></div><div style={{left:'25%'}}><i/>3s<br/><b>open</b></div><div style={{left:'58%'}}><i/>7s<br/><b>close starts</b></div><div style={{left:'83%'}}><i/>10s<br/><b>closed</b></div><div style={{left:'100%'}}><i/>12s</div></div>
          <p>Our repeated panel cycle opens for 3 seconds, holds open for 4, closes for 3 and holds closed for 2. Repeating the same open value across a time interval creates the four-second hold.</p>
          <h3>Exactly what happens when you click “Open doors”</h3>
          <div className="animation-pipeline"><div><span>1</span><div><b>The button identifies an action</b><p>The panel finds <code>open_doors</code> in <code>datatable.json</code>. Its mode is <code>clip</code>, its range is frames 1560–1848, and <code>loop</code> is true.</p></div></div><div><span>2</span><div><b>The timeline is prepared</b><p>Panel code sets the timeline start and end, moves current time to frame 1560, enables looping and calls Play.</p></div></div><div><span>3</span><div><b>USD evaluates each moment</b><p>At every displayed frame, the stage reads the time-sampled rotations for the left- and right-door joints. The renderer redraws their new positions.</p></div></div><div><span>4</span><div><b>The cycle repeats</b><p>When frame 1848 is reached, looping returns to 1560. Nothing is “recorded again”; the same authored samples are evaluated repeatedly.</p></div></div></div>
          <h3>The real Open Doors frame plan</h3>
          <Callout title="Why does it begin at frame 1560?"><p><b>1560 is only the reserved starting address of this clip on our master timeline.</b> It does not mean the doors take 1,560 frames to open. Earlier timeline regions are reserved for steering, wheel spin and other animations, so Open Doors was placed in its own non-overlapping slot—like parking different actions in separate spaces.</p></Callout>
          <div className="timeline-slots"><div><code>0–160</code><span>Steering</span></div><div><code>960–1200</code><span>Wheel spin</span></div><div><code>1240–1528</code><span>Open everything</span></div><div className="active"><code>1560–1848</code><span>Open doors · 12 sec</span></div><div><code>2200–2296</code><span>Drive forward</span></div><div><code>2320–2416</code><span>Drive backward</span></div></div>
          <div className="formula"><span>Convert a global frame to time inside this clip</span><b>(current frame − 1560) ÷ 24</b><small>Example: (1632 − 1560) ÷ 24 = 3 seconds. Frame 1560 therefore equals local time 0.</small></div>
          <div className="frame-plan"><div className="frame-head"><b>Frame</b><b>Elapsed</b><b>Door value</b><b>What you see</b></div><div><code>1560</code><span>0 sec</span><span>Closed</span><span>The cycle begins</span></div><div><code>1632</code><span>3 sec</span><span>Open</span><span>Both doors finish opening</span></div><div><code>1728</code><span>7 sec</span><span>Still open</span><span>The four-second open hold finishes</span></div><div><code>1800</code><span>10 sec</span><span>Closed</span><span>Both doors finish closing</span></div><div><code>1848</code><span>12 sec</span><span>Still closed</span><span>The two-second closed hold finishes; loop restarts</span></div></div>
          <Callout kind="project" title="Why the Hold Doors Open button behaves differently"><p><code>hold_doors</code> has mode <code>pose</code> and frame <code>1728</code>. The panel stops playback and sets one exact time. Because the timeline is not advancing, the doors remain open for as long as you want. A pose selects a moment; a clip plays through many moments.</p></Callout>
          <h3>Keyframes and interpolation</h3><p>A keyframe (time sample) stores an important value at a chosen time. Between two keys, interpolation calculates intermediate values. Linear interpolation moves at constant speed. Smooth curves ease in and out. Step interpolation jumps without blending.</p>
          <Code>{`# Simplified door-joint rotation samples
rotateAt(1560) = 0°       # closed
rotateAt(1632) = 68°      # open after 3 seconds
rotateAt(1728) = 68°      # same value: hold open for 4 seconds
rotateAt(1800) = 0°       # close over 3 seconds
rotateAt(1848) = 0°       # hold closed for 2 seconds`}</Code>
          <p>The hold is not a pause instruction embedded inside the door. It emerges from two equal values separated in time. Between frames 1632 and 1728, evaluating the rotation keeps producing 68°, so the door stays still while the playhead continues moving.</p>
          <div className="compare"><div><h4>What we authored</h4><p>Important rotation values at closed, open, hold and closing frames.</p><code>joint rotation @ frame 1560, 1632…</code></div><div><h4>What Composer calculates</h4><p>All intermediate joint orientations needed to display smooth movement between those authored samples.</p><code>evaluate(currentTime)</code></div></div>
          <h3>Skeleton animation</h3><p>The imported FBX car contains a skeleton-like joint hierarchy for doors, hoods, steering and wheels. Rotating the correct joint moves all geometry influenced beneath it. This is why identifying real door and hood joints was better than pretending the entire car was one static mesh.</p>
          <div className="joint-tree"><b>/World/Car</b><span>└─ ZAZ_965_fbx_skel</span><span>　├─ left door joint → left door mesh</span><span>　├─ right door joint → right door mesh</span><span>　├─ front trunk joint → front trunk mesh</span><span>　├─ rear hood joint → rear hood mesh</span><span>　└─ steering parents → front-wheel spin children</span></div>
          <h3>Drive Forward combines two animation systems</h3><p>The <code>drive_forward</code> action plays frames 2200–2296 for four seconds. During that same time, panel code smoothly translates <code>/World/Car</code> 350 units along Z while the USD clip rotates all four wheels.</p>
          <div className="split-motion"><div><RotateCw/><b>Wheel animation layer</b><p>Contains dense, axle-centered rotation samples. It handles the visual rolling of the four tires.</p></div><span>+</span><div><ArrowRight/><b>Panel movement task</b><p>Reads the car’s current position and smoothly changes its Z translation by 350 units.</p></div><span>=</span><div><PlayCircle/><b>Driving result</b><p>The whole car travels forward while its wheels spin at the same time.</p></div></div>
          <Code>{`start = current_position_of("/World/Car")
for each moment during 4 seconds:
    t = smoothstep(elapsed / duration)
    car.z = start.z + (350 * t)
    timeline evaluates wheel rotation for the same moment`}</Code>
          <p>We start from the <b>current</b> car position, not a fixed origin. That is why pressing Drive Forward again continues from wherever the previous movement stopped.</p>
          <h3>Quaternions and wobble</h3><p>Quaternions represent rotation without the classic gimbal-lock problems of Euler angles. But <code>q</code> and <code>-q</code> describe the same orientation. If adjacent samples alternate signs, interpolation may take an undesirable path. We enforced sign continuity by checking the quaternion dot product and negating the next sample when needed.</p>
          <Code>{`if dot(previous_quaternion, next_quaternion) < 0:
    next_quaternion = -next_quaternion`}</Code>
          <p>The drive clips also gained one sample per frame—97 samples across each four-second range—so the front-wheel compensation remained stable while steering parents were involved.</p>
          <Callout title="Timeline versus Curve Editor"><p>The timeline answers <b>when</b>. A Curve Editor shows <b>how a numeric value changes</b> between keys. Our generated USD samples can play on the timeline even though we authored them with a script rather than manually dragging curves.</p></Callout>
        </Lesson>

        <Lesson id="datatable" eyebrow="Chapter 08 · Reusable tools" title="The Data Table tells one UI how to serve this car" intro="This is the bridge between project-specific information and reusable panel logic. It is useful precisely because it is not the UI and not the USD asset." done={completed.includes('datatable')} onDone={()=>toggle('datatable')}>
          <div className="flow"><div><Database/><b>datatable.json</b><span>Options + actions + paths</span></div><ChevronRight/><div><Code2/><b>Python panel</b><span>Build buttons</span></div><ChevronRight/><div><Box/><b>USD APIs</b><span>Apply changes</span></div></div>
          <h3>A screenshot of our real Data Table</h3>
          <figure className="datatable-shot"><img src="/datatable-json.svg" alt="Annotated screenshot of the ZAZ-965 datatable.json showing defaults, environment options, Open Doors animation and Drive Forward animation"/><figcaption>This is a focused screenshot of the actual structures currently used by the mini demo. The complete file also contains layer descriptions, material mappings, part records and the rest of the animation actions.</figcaption></figure>
          <div className="annotation-grid"><div><span className="note-one">1</span><p><b>Defaults</b> are the selections used when the panel first resolves the configuration: original body paint, original wheels and Desert Road.</p></div><div><span className="note-two">2</span><p><b>Control options</b> are selectable values that are not attached to a particular part record. Here they generate Desert Road and Studio choices.</p></div><div><span className="note-three">3</span><p><b>Open Doors</b> is a reusable clip action. The label becomes button text; the frame range tells the timeline what to play; loop tells it to repeat.</p></div><div><span className="note-four">4</span><p><b>Drive Forward</b> adds action-specific data: Z is the car’s forward axis and 350 is the distance moved while frames 2200–2296 spin the wheels.</p></div></div>
          <h3>What our table currently exposes</h3><Code>{`"defaults": {
  "color": "original",
  "wheel_finish": "original",
  "environment": "desert_road"
}`}</Code>
          <p>Trim, interior and mirror controls are hidden because those choices do not meaningfully change this imported car. The underlying educational USD variants may remain, but the user-facing menu stays honest.</p>
          <h3>Animation actions are data too</h3><Code>{`{
  "id": "drive_forward",
  "label": "Drive forward + wheel spin",
  "mode": "drive",
  "start_frame": 2200,
  "end_frame": 2296,
  "axis": "z",
  "distance": 350
}`}</Code>
          <p>The panel understands the general meaning of a <code>drive</code> action. The table supplies this vehicle’s label, timeline range, direction and distance. A second vehicle could use the same panel code with different data.</p>
          <div className="compare"><div><h4>Without a Data Table</h4><p>Every button label, option and frame range is written directly into Python. Changing a project choice means editing application logic.</p></div><div><h4>With a Data Table</h4><p>Python stays reusable. The project describes itself in JSON, and the panel builds the appropriate controls.</p></div></div>
          <Callout title="The boundary to remember"><p>The Data Table can <b>expose and configure</b> capabilities. It cannot manufacture geometry, materials or animation. “Add garage” requires both a garage environment in USD and a corresponding table option.</p></Callout>
        </Lesson>

        <Lesson id="mcp" eyebrow="Chapter 09 · Automation" title="MCP is a controlled conversation with Composer" intro="The router lets an external assistant discover and call specific scene tools. It is more structured than blindly clicking the screen and safer than exposing arbitrary code execution." done={completed.includes('mcp')} onDone={()=>toggle('mcp')}>
          <h3>The route</h3><div className="flow"><div><Code2/><b>Codex</b><span>Requests a scene action</span></div><ChevronRight/><div><Network/><b>Router :9905</b><span>Dispatches the tool call</span></div><ChevronRight/><div><Box/><b>Composer :9910</b><span>Runs it against the live stage</span></div></div>
          <p>The MCP server describes tools with names, inputs and outputs. Codex can discover these tools and call them. The router exists as a stable front door, while the Composer bridge talks to the live application.</p>
          <h3>What this enables</h3><ul><li>Inspect stage paths and prim properties.</li><li>Change variant selections.</li><li>Move or rotate scene objects.</li><li>Set timeline ranges and trigger known actions.</li><li>Save or validate the working scene.</li><li>Automate repetitive checks without relying on screen coordinates.</li></ul>
          <Callout kind="careful" title="Running is not the same as visible"><p>The PowerShell message “Started router” means the service is listening. It does not mean Composer was launched. Starting with <code>-LaunchComposer</code> opens the application and provides live scene awareness.</p></Callout>
          <h3>MCP versus the Data Table</h3><p>MCP is an <b>external tool interface</b>. The Data Table is <b>internal project configuration</b>. MCP may ask Composer to change a selection; the Data Table tells our custom panel which selections it should present.</p>
        </Lesson>

        <Lesson id="debugging" eyebrow="Chapter 10 · Lessons from mistakes" title="Every bug taught us a reusable concept" intro="Debugging is not separate from learning. Each issue in this demo points to a principle you can reuse in future USD and real-time projects." done={completed.includes('debugging')} onDone={()=>toggle('debugging')}>
          <div className="debug-list"><div><span>01</span><div><h3>Missing grid texture</h3><p><b>Symptom:</b> a UsdToMdl warning referenced an old Kit cache path.</p><p><b>Lesson:</b> material networks depend on external image assets; a valid USD path can still point to a missing file.</p></div></div><div><span>02</span><div><h3>Animation looked instantaneous</h3><p><b>Symptom:</b> clicking “Everything open” jumped to an open pose.</p><p><b>Lesson:</b> a pose is one evaluated time; visible motion requires playing through a time range.</p></div></div><div><span>03</span><div><h3>Panel scrolled away after clicks</h3><p><b>Symptom:</b> rebuilding the whole UI reset the scroll position.</p><p><b>Lesson:</b> update only changed labels and button states; preserve interface state when data changes.</p></div></div><div><span>04</span><div><h3>Front wheel orbited the axle</h3><p><b>Symptom:</b> the tire travelled in a circle instead of spinning.</p><p><b>Lesson:</b> rotations occur around transform origins; use the correct axis, pivot and hierarchy.</p></div></div><div><span>05</span><div><h3>Car moved sideways</h3><p><b>Symptom:</b> “forward” translated horizontally across the road.</p><p><b>Lesson:</b> never assume an asset’s forward axis. Inspect the local/world axis orientation.</p></div></div><div><span>06</span><div><h3>Front tires jittered</h3><p><b>Symptom:</b> rear wheels were stable while steering wheels wobbled.</p><p><b>Lesson:</b> dense samples and quaternion sign continuity matter when combined joint transforms interpolate.</p></div></div></div>
          <h3>A calm debugging loop</h3><ol><li>Describe the visible symptom precisely.</li><li>Identify the smallest prim/property involved.</li><li>Check space, time, path and layer strength.</li><li>Change one cause at a time.</li><li>Validate both the intended result and what should remain unchanged.</li></ol>
        </Lesson>

        <Lesson id="files" eyebrow="Chapter 11 · Navigation" title="Know which file owns which concern" intro="You do not need to memorize every file. You need a map that tells you where to look when a particular kind of change is requested." done={completed.includes('files')} onDone={()=>toggle('files')}>
          <div className="file-table"><div className="file-head"><b>File</b><b>Responsibility</b><b>Edit it when…</b></div>{[
            ['working_scene.usda','Root assembly and layer stack','You need to change what composes the final stage'],
            ['datatable.json','Visible options, defaults and actions','You need to expose/hide a control or adjust action data'],
            ['mini_carpaint_variants.usda','Body color alternatives','You add or change a real paint variant'],
            ['mini_model_variants.usda','Wheel/configuration variants','You change wheel finish alternatives'],
            ['zaz965_wheel_spin.usdc','Generated dense animation samples','Regenerate wheel/drive animation; do not hand-edit binary data'],
            ['build_wheel_spin_layer.py','Animation-generation logic','You change pivots, clip ranges or sampling strategy'],
            ['mini_omk_panel.py','Reusable UI behavior','You add a new action mode or change panel interaction logic'],
            ['validate_usd_stack.py','Automated expectations','A required layer, variant or animation invariant changes'],
            ['start-omniverse.ps1','Stack launcher','Ports, startup services or launch behavior change'],
            ['RESUME_ON_NEW_PC.md','Handoff and recovery notes','The project state or manual startup process changes'],
          ].map(r=><div key={r[0]}><code>{r[0]}</code><span>{r[1]}</span><span>{r[2]}</span></div>)}</div>
          <h3>Manual startup</h3><Code>{`cd D:\\Omniverse
.\\start-omniverse.ps1 -LaunchComposer`}</Code>
          <p>This starts the supporting services and launches Composer. To stop the stack later, use <code>.\stop-omniverse.ps1</code>.</p>
          <h3>Before calling a feature finished</h3><ul className="checklist"><li><Check/> The intended button performs a visible, understandable change.</li><li><Check/> Original appearance can be restored.</li><li><Check/> Repeated clicks do not move the panel unexpectedly.</li><li><Check/> Animation starts, holds, closes and loops as described.</li><li><Check/> Save and reopen preserves the stage setup.</li><li><Check/> Validation reports expected layers, variants, prims and samples.</li></ul>
        </Lesson>

        <Lesson id="atlas" eyebrow="Chapter 12 · Visual map" title="See how the entire ZAZ project is organized" intro="Use this chapter when the project feels like too many files and panels. It connects the real Composer interface to the Stage hierarchy, layer stack, materials, Data Table, animation and MCP runtime." done={completed.includes('atlas')} onDone={()=>toggle('atlas')}>
          <VisualAtlas/>
          <h3>Explore the real Stage and composition</h3>
          <p>Open each card slowly. First identify what panel you are seeing, then connect it to the USD concept underneath.</p>
          <div className="screen-grid">
            <ScreenCard src="/composer-layer-stack.png" title="The complete layer stack"><p><b>Root Layer</b> is the authoring file currently open. Every gray row beneath it is a sublayer contributing opinions to the final Stage. The wheel-spin layer is strongest in this displayed sublayer order, followed by paint/model/interior variants, bindings, materials, assembly, metadata, lights and environments.</p><p>The eye icons mute a layer temporarily for diagnosis. The lock icons control whether it can be edited. Muting is an excellent way to ask: “What does this layer contribute?”</p></ScreenCard>
            <ScreenCard src="/composer-stage-tree.png" title="The composed Stage tree"><p>This is not a list of files. It is the <b>composed hierarchy</b> produced after those files combine. <code>/World/Car</code> contains the referenced ZAZ asset; <code>/World/Looks</code> contains project materials; <code>/Environment</code> contains ground, cameras, lights and projected HDR environments.</p><p>The Type column reveals schemas such as Xform, Scope, SkelRoot, Mesh and Material.</p></ScreenCard>
            <ScreenCard src="/car-reference-variants.png" title="Reference and variants on /World/Car"><p>The References panel proves that <code>/World/Car</code> reuses <code>zaz965_converted.usd</code>. The asset is not copied into the assembly file.</p><p>The Variants panel shows named selections—color, trim, wheel finish, mirror version and interior—on the same prim. A reference answers “which asset?”; a variant answers “which alternative of that asset?”</p></ScreenCard>
            <ScreenCard src="/material-binding-property.png" title="A real source-material binding"><p>The selected left-door mesh has a relationship to <code>/World/Car/Looks/material_001_XSI__Humpback</code>. That path is the material prim providing its appearance.</p><p><b>Weaker than Descendants</b> is binding strength metadata. It helps USD decide which binding wins when a more specific descendant also supplies one.</p></ScreenCard>
          </div>
          <h3>Read material inputs like a recipe</h3>
          <div className="screen-grid">
            <ScreenCard src="/bluepaint-inputs.png" title="BluePaint shader inputs"><p><code>diffuseColor</code> supplies cyan-blue RGB values. Metallic is 0, so it behaves as painted dielectric rather than bare metal. Roughness 0.5 produces broader, softer reflections. Clearcoat is currently 0.</p></ScreenCard>
            <ScreenCard src="/wheelcream-inputs.png" title="Wheel-cream shader inputs"><p>The warm RGB color creates the cream finish. Metallic 0.35 and roughness 0.35 make it more reflective and tighter-highlighted than BluePaint. This is why two similarly simple materials can react differently to the same environment.</p></ScreenCard>
          </div>
          <Callout title="Material equation to remember"><p><b>Geometry shape + material inputs + texture maps + lighting/environment = final pixels.</b> Changing one input never explains the whole appearance by itself.</p></Callout>
          <h3>Read the Data Table as executable project documentation</h3>
          <div className="screen-grid datatable-gallery">
            <ScreenCard src="/datatable-defaults.png" title="Defaults and environment options"><p>Defaults define the starting state. Control options define which buttons the reusable panel should create. They do not themselves load geometry—the corresponding USD environment capability must already exist.</p></ScreenCard>
            <ScreenCard src="/datatable-material-bindings.png" title="Color-to-material path map"><p>This lookup converts a friendly choice such as <code>red</code> into the exact USD target <code>/World/Looks/RedPaint</code>. It separates human-facing labels from scene addresses.</p></ScreenCard>
            <ScreenCard src="/datatable-animation-actions.png" title="Pose, clip and hold actions"><p>A pose stores one frame. A clip stores a start/end range and may loop. Notice how Open Doors and Hold Doors Open are separate actions: one plays visible movement; the other stops on an exact open frame.</p></ScreenCard>
            <ScreenCard src="/datatable-drive-actions.png" title="Wheel spin and driving actions"><p>Wheel spin is a timeline clip. Drive actions add spatial instructions: axis Z and distance ±350. The panel combines car translation with the USD wheel-animation range.</p></ScreenCard>
          </div>
          <h3>The real Composer workspace</h3>
          <ScreenshotLesson src="/composer-datatable-panel.png" alt="USD Composer showing the ZAZ scene, Mini DataTable Explorer and Configurator Samples" title="Three systems visible in one screen" caption="The viewport is the composed result, the right panel is our data-driven controller, and the lower browser supplies reusable assets and materials." points={[{label:'Viewport = result. ',text:'It displays the current Stage at the current time using the active renderer.'},{label:'Mini DataTable Explorer = controller. ',text:'It reads project JSON and translates selections into variants, timeline actions and transforms.'},{label:'Configurator Samples = reference library. ',text:'These examples teach patterns, but opening one as a scene can replace the current workspace view.'},{label:'Property panel = inspection. ',text:'When a prim is selected, this area reveals authored attributes, relationships and bindings.'}]}/>
          <h3>Where materials come from</h3>
          <ScreenshotLesson src="/composer-material-library.png" alt="Composer Materials browser showing automotive paint presets below the ZAZ scene" title="Library materials versus Stage materials" caption="The Library tab is a catalog of reusable definitions. A material becomes part of this project only after it is created or copied into the current Stage and given a prim path." points={[{label:'Library presets are sources. ',text:'The colored spheres preview packaged automotive shader networks.'},{label:'Current Stage is ownership. ',text:'Project materials live as prims—normally under /World/Looks—and save with an authored layer.'},{label:'Create New builds a material prim. ',text:'Its shader inputs define base color, roughness, metallic response and other surface behavior.'},{label:'Binding completes the connection. ',text:'A material affects nothing until geometry points to it through material:binding.'}]}/>
          <div className="binding-diagram"><div><Box/><b>Body geometry</b><code>/World/Car/.../body</code></div><span>material:binding</span><div><Sparkles/><b>Material prim</b><code>/World/Looks/RedPaint</code></div><span>shader inputs</span><div><Gauge/><b>Rendered pixels</b><code>color + roughness + light</code></div></div>
          <h3>How to read the organization</h3>
          <div className="numbered"><div><span>1</span><p><b>Stage paths answer “where?”</b> They identify the car, environment, material, joint or mesh being targeted.</p></div><div><span>2</span><p><b>Layers answer “who authored this?”</b> They separate source geometry from our paint, wheel and animation opinions.</p></div><div><span>3</span><p><b>Relationships answer “what is connected?”</b> Material bindings connect geometry to Looks; references connect an assembly prim to an asset file.</p></div><div><span>4</span><p><b>Time samples answer “what changes when?”</b> Door joints, hood joints and wheels evaluate different values as the timeline advances.</p></div><div><span>5</span><p><b>The Data Table answers “what should the UI expose?”</b> It keeps labels, paths, options and action ranges outside reusable panel logic.</p></div><div><span>6</span><p><b>MCP answers “how can another tool operate it?”</b> The router exposes controlled inspection and scene actions through the live Composer bridge.</p></div></div>
          <Callout kind="project" title="The complete ZAZ pipeline"><p><code>FBX source → converted USD asset → referenced Car prim → specialized variant/animation layers → composed working scene → DataTable-driven Kit panel → Composer viewport</code>. MCP sits beside the panel as another controlled way to inspect or operate the same live Stage.</p></Callout>
        </Lesson>

        <Lesson id="concept-library" eyebrow="Chapter 13 · Complete reference" title="Every concept we learned—together in one place" intro="This is the project’s complete knowledge inventory. It combines the early cube experiment, the real ZAZ-965 configurator, every animation and material lesson, the custom Kit panel, MCP automation, and the bugs that taught us how USD really behaves." done={completed.includes('concept-library')} onDone={()=>toggle('concept-library')}>
          <ConceptLibrary/>
        </Lesson>

        <Lesson id="practice" eyebrow="Chapter 14 · Make it yours" title="Practice until the ideas feel natural" intro="Reading builds recognition. Small experiments build understanding. These exercises are ordered from safe data edits to deeper USD work." done={completed.includes('practice')} onDone={()=>toggle('practice')}>
          <h3>Guided exercises</h3><div className="exercise-grid"><div><span>Easy · 10 min</span><h4>Rename a button</h4><p>Change an animation <code>label</code> in the Data Table, reload it and confirm only the UI wording changes.</p></div><div><span>Easy · 15 min</span><h4>Change driving distance</h4><p>Reduce <code>distance</code> from 350 to 150. Predict the result before pressing Drive Forward.</p></div><div><span>Medium · 25 min</span><h4>Trace a color click</h4><p>Write the path from JSON option → panel callback → variant selection → material binding → rendered pixels.</p></div><div><span>Medium · 30 min</span><h4>Inspect layer strength</h4><p>Select a prim and identify which layer authored the winning material or visibility opinion.</p></div><div><span>Challenge · 45 min</span><h4>Add a green paint</h4><p>Create the material and variant first, validate it, then expose <code>green</code> through the Data Table.</p></div><div><span>Challenge · 60 min</span><h4>Create a camera preset</h4><p>Author a camera prim, then design a small data-driven action that moves the viewport to that shot.</p></div></div>
          <h3>Knowledge check</h3><div className="quiz">{quiz.map((item,i)=><div className="quiz-item" key={item.q}><b>{i+1}. {item.q}</b><div>{item.options.map((o,j)=><button key={o} onClick={()=>setAnswers(v=>({...v,[i]:j}))} className={answers[i]===j?(j===item.answer?'selected correct':'selected wrong'):''}>{answers[i]===j&&(j===item.answer?<Check/>:<X/>)}{o}</button>)}</div>{answers[i]!==undefined&&<p className={answers[i]===item.answer?'answer-good':'answer-bad'}>{item.why}</p>}</div>)}</div>{Object.keys(answers).length===quiz.length&&<div className="score"><Gauge/><div><b>{score}/{quiz.length} correct</b><p>{score===quiz.length?'Excellent—your mental model is solid.':score>=3?'Good foundation. Review the explanations for the missed questions.':'Take another slow pass through Chapters 1–8, then retry.'}</p></div></div>}
          <h3>Searchable glossary</h3><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search terms such as prim, layer, material…"/></label><div className="glossary">{filteredGlossary.map(([term,meaning])=><details key={term}><summary>{term}<ChevronRight/></summary><p>{meaning}</p></details>)}</div>
        </Lesson>

        <section className="finish"><Sparkles/><p className="eyebrow">You built more than a car demo</p><h2>You built a small, layered, data-driven USD application.</h2><p>Return to this guide whenever a word or workflow feels fuzzy. The goal is not to memorize everything at once—it is to know how the pieces relate and where to look next.</p><a href="#top">Back to the beginning <ArrowRight/></a></section>
      </article>
    </div>
  </main>;
}
